version: "3.6"
services:
  fai:
    # http://10.4.1.245:6883
    build: .
    shm_size: 16GB 
    # image: fastai/fastai:2022-05-29 
    # image: xx___pytorch/pytorch:1.11.0-cuda11.3-cudnn8-runtime
    ports:
      - "6883:8888"
    volumes:
      - ./acup:/acup
      #- ./workspace:/workspace
      - ./home/dot/jupyter:/root/.jupyter
    working_dir: /acup  

    command: ["bash", "-c", "source /etc/bash.bashrc && jupyter notebook --notebook-dir=/acup --ip 0.0.0.0 --no-browser --allow-root"]  

    # keep container running..
    # command: tail -f /dev/null
    # command: /bin/bash -c "pwd && /bin/bash"
    # tty: true

