version: "3.6"
services:
  tf:
    # http://10.4.1.245:8890
    # build: .
    image: tensorflow/tensorflow:2.7.1-jupyter
    ports:
      - "8890:8888"
    volumes:
      - ./notebook:/tf/notebook
      - ./home/dot/jupyter:/root/.jupyter

