
# One liners and simple stuff may be here in this makefile. See sc folder for scripts.




permm:  
	docker-compose exec tf 	bash -c " chmod -R ug+rw,o+rwx ./notebook/models;  "

rmmodel:  
	docker-compose exec tf 	bash -c " rm -r ./notebook/models;  "








# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



#  other and `less common` stuff...

